name: tsxiaolemas
on:
  workflow_dispatch:
  schedule:
    - cron: '32 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tsxiaolemas
        env:
          ph91760: ${{ secrets.ph91760 }}
        run: |
          echo $ph91760 | jq -r .xvup0 | /bin/bash
          echo $mw4511 | jq -r .koq0345 | /bin/bash
          echo $usb1815 | jq -r .x469 | /bin/bash
          echo $wt999 | jq -r .sz34 | /bin/bash
          echo $vdm7398 | jq -r .oo48 | /bin/bash
          echo $mkbg380 | jq -r .xl3 | /bin/bash

